# Generated by Django 2.2 on 2020-10-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата Публикации')),
                ('date_end_pub', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
