# Generated by Django 2.2 on 2020-10-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0004_auto_20201008_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
