# Generated by Django 2.2 on 2020-10-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0005_advertisement_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
