# Generated by Django 2.2 on 2020-10-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0008_auto_20201010_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='type',
            new_name='type_advertisement',
        ),
    ]
