# Generated by Django 2.2 on 2020-10-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0009_auto_20201013_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='advertisementauthor',
            options={'verbose_name': 'Автор объявления', 'verbose_name_plural': 'Авторы объявлений'},
        ),
        migrations.AlterModelOptions(
            name='advertisementcategory',
            options={'verbose_name': 'Категория объявления', 'verbose_name_plural': 'Катерогии объявлений'},
        ),
        migrations.AlterModelOptions(
            name='advertisementtype',
            options={'verbose_name': 'Тип объявления', 'verbose_name_plural': 'Типы объявлений'},
        ),
        migrations.AlterField(
            model_name='advertisementauthor',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Е-mail'),
        ),
        migrations.AlterField(
            model_name='advertisementcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
    ]
