# Generated by Django 2.2 on 2020-10-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0010_auto_20201013_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='type_advertisement',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertisement_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_type', to='advertisements_app.AdvertisementType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_author', to='advertisements_app.AdvertisementAuthor', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_category', to='advertisements_app.AdvertisementCategory', verbose_name='Категория'),
        ),
    ]
