# Generated by Django 2.2 on 2020-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0012_auto_20201015_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='date_end_pub',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания публикации'),
        ),
    ]
